#!/bin/sh
### BEGIN INIT INFO
# Provides:          bme280mqtt
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       MQTT data publisher of bme280 readings
### END INIT INFO

SCRIPT=/home/pi/src/bme280_mqtt_provider/bme280_mqtt_provider
RUNAS=pi
ID='!!!ID not set, check init.d script!!!'
TOPIC=sensors
BROKER=''
PERIOD=60

PIDFILE=/var/run/bme280mqtt.pid
LOGFILE=/var/log/bme280mqtt.log

start() {
  if [ -f /var/run/$PIDFILE ] && kill -0 $(cat /var/run/$PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  touch $LOGFILE
  chown pi $LOGFILE
  local CMD="$SCRIPT -broker "$BROKER" -topic "$TOPIC" -id "$ID" -period $PERIOD &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f bme280mqtt remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac